server:
  port: 9211

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  data:
    redis:
      host: 172.20.50.204
      port: 6379
      database: 8
      password: love!123
  cloud:
    nacos:
      server-addr: 172.20.89.135:8848
      discovery:
        group: DEFAULT_GROUP
        namespace: public
      config:
        group: DEFAULT_GROUP
        namespace: dev
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml
security:
  captcha:
    enabled: true
    length: 4

